version: '3'
services:
            
    radix-server:
        image: radix-server
        container_name: radix-server
        environment:
            - RADIX_SERVER_PORT=${RADIX_SERVER_PORT}
            - MONGODB_HOST=${MONGODB_HOST}
            - MONGODB_PORT=${MONGODB_PORT}
            - spring.profiles.active=docker-local
        ports:
            - "${RADIX_SERVER_PORT}:${RADIX_SERVER_PORT}"