FROM java:8-jre

MAINTAINER Tony Lopez <tony.lopez1013@gmail.com>

COPY ./target/applink-service-0.0.1-SNAPSHOT.jar /app/applink-service.jar

CMD ["java", "-jar", "/app/applink-service.jar"]

EXPOSE 9001